name: CI
on:
  pull_request:
  push:
    branches: ['main']
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Npm Install
      run: npm ci
    - name: Build app
      run: npm run build
    - run: npm run lint
